// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Demo.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__MY_MSGS_MSG_DEMO_HPP
#define FAST_DDS_GENERATED__MY_MSGS_MSG_DEMO_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(DEMO_SOURCE)
#define DEMO_DllAPI __declspec( dllexport )
#else
#define DEMO_DllAPI __declspec( dllimport )
#endif // DEMO_SOURCE
#else
#define DEMO_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define DEMO_DllAPI
#endif // _WIN32

namespace my_msgs {

namespace msg {

/*!
 * @brief This class represents the structure Demo defined by the user in the IDL file.
 * @ingroup Demo
 */
class Demo
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Demo()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Demo()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Demo that will be copied.
     */
    eProsima_user_DllExport Demo(
            const Demo& x)
    {
                    m_name = x.m_name;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Demo that will be copied.
     */
    eProsima_user_DllExport Demo(
            Demo&& x) noexcept
    {
        m_name = std::move(x.m_name);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Demo that will be copied.
     */
    eProsima_user_DllExport Demo& operator =(
            const Demo& x)
    {

                    m_name = x.m_name;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Demo that will be copied.
     */
    eProsima_user_DllExport Demo& operator =(
            Demo&& x) noexcept
    {

        m_name = std::move(x.m_name);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Demo object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Demo& x) const
    {
        return (m_name == x.m_name);
    }

    /*!
     * @brief Comparison operator.
     * @param x Demo object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Demo& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const std::string& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            std::string&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const std::string& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport std::string& name()
    {
        return m_name;
    }



private:

    std::string m_name;

};

} // namespace msg

} // namespace my_msgs

#endif // _FAST_DDS_GENERATED_MY_MSGS_MSG_DEMO_HPP_


